name = 'ASR Paper Initial Guess Detumble Config '


chaser_name_in_urdf = 'ChaserSC'
target_name_in_urdf = "TargetSC"

[paths]
sc_path = 'planarSCDetumble_no_collision.urdf'
initial_guess = 'detumbleTraj.pkl'

[epsilons]
unit_quaternion = 0.01
dynamics_equation = 0.01
final_velocity = 0.1

[initial_state]
position = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.72, 1.2, 0.72]
velocity = []
acceleration = []

[trajopt_options]
knot_points = 100
delta_t_min = 0.01
delta_t_max = 0.2
equal_dt = true
use_actuation_limits = true
use_initial_guess = false

[trajopt_cost_weights]
total_time = 1
base_torques = 1
base_forces =10
joint_torques = 1
final_base_velocity = 1e8
final_joint_velocity = 1e4


[joint_limits]
base_torque_limit = [2.5, 2.5, 2.5]
base_force_limit = [2, 2, 2]
joint_torque_limit = 0.5

[solver_options]
# solver_name = 'ipopt'
solver_name = 'snopt'